name: '📚 latest Blog'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 12 ? * MON	'

jobs:
  update_blogs:
    name: 'Update With Latest Blogs'
    runs-on: ubuntu-latest
    steps:
      - name: '📥  Fetching Repository Contents'
        uses: actions/checkout@main

      - name: '📚  Hashnode Updater'
        uses: 'varunsridharan/action-hashnode-blog@1.1.1'
        with:
          USERNAME: 'coluzziandrea' # Hashnode Username
          COUNT: 5 # MAX Visisble
          STYLE: 'blog-left'
          BLOG_URL: 'https://coluzziandrea.hashnode.dev/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
